---

- name: get ssh key for remote run
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    AWS_DEFAULT_REGION: "{{ region }}"
  pre_tasks:
  - name: Create temporary directory
    file:
      path: "{{ playbook_dir }}/tmp"
      state: directory
  - name: Fetch private key to local file
    copy:
      content: "{{ lookup('aws_ssm', '/techops/security/qualys/qualys_ami_test') }}"
      dest: "{{ playbook_dir }}/tmp/{{ environ }}.key"
      mode: 0600

#- name: remove sudo requiretty so we can use pipelining
#  hosts: example_servers
#  ansible_ssh_pipelining: no
#  become: yes
#  vars:
#    ansible_ssh_private_key_file: "tmp/{{ environ }}.key"
#  tasks:
#    - name: remove requiretty
#      lineinfile:
#        dest: /etc/sudoers
#        line: 'Defaults    requiretty'
#        state: absent
#      tags: notty
##
##
#- name: Remove ssh keys at the end of the run
#  hosts: localhost
#  connection: local
#  gather_facts: false
#  environment:
#    AWS_DEFAULT_REGION: "{{ region }}"
#  tasks:
#    - name: list ssh keys
#      find:
#        paths: tmp
#        patterns: "*key"
#      register: ssh_keys
#      tags: find_ssh
#    - name: remove ssh keys
#      file:
#        path: "{{ item.path }}"
#        state: absent
#      with_items: "{{ ssh_keys.files }}"
#      tags: find_ssh
#      changed_when: False

# - name:
#   hosts:
#   vars:
#   pre_tasks:
#   roles:
#   tasks:
#   post_tasks:
