# Modules for deployment playbook.

---

- src: git+ssh://git@github.com/SPSCommerce/ansible-inventory.git
  path: roles
  name: inventory

- src: git+ssh://git@github.com/SPSCommerce/ansible-role-cfn-stack.git
  path: roles
  name: stack
